keys:
  - &alpha age10ngxes5qkqpacg3h4zwutw2kgpp2p38je2q6mtsupnejaf30eyaq9kvtxy
  - &omega age18znyg2d4fx7fn05f9m077aqxwkv8z2f7ry7z34vycr8vsnvelp3sxg7dwh
  - &omega2 age1vcxzvcnre9jt2fg6puhvtt4v2hjexcpqxeld526mdnw9073g29ksjxkm7k
  - &mbp age16hsjulgya2vepqjc3clknn4ufz90xetj4nu9jekw3g006p50sq8q6tf6ph
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *alpha
          - *omega
          - *mbp
