keys:
  - &omega age18znyg2d4fx7fn05f9m077aqxwkv8z2f7ry7z34vycr8vsnvelp3sxg7dwh
  - &mbp-work age16hsjulgya2vepqjc3clknn4ufz90xetj4nu9jekw3g006p50sq8q6tf6ph
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *omega
          - *mbp-work
